# From **Azure AD B2C** portal `App registrations` blade, select **Endpoints**, Access `Azure AD B2C OpenID Connect metadata document`(Global cloud format may looks like
#`https://{your-tenant-name}.b2clogin.com/{your-tenant-name}.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration`,
# China Cloud looks like `https://{your-tenant-name}.b2clogin.cn/{your-tenant-name}.partner.onmschina.cn/<policy-name>/v2.0/.well-known/openid-configuration`) replace <policy-name> with your sign up or sign in user flow name.
spring:
  security:
    oauth2:
      client:
        provider:
          sign-up-or-sign-in:
            # You can find your authorization-uri from the **Endpoints** with `Azure AD B2C OAuth 2.0 authorization endpoint (v2)` and replace `<policy-name>` with your sign up or sign in user flow
            authorization-uri: ${your-authorization-uri}
            # You can find your `token-uri` from the result page of Azure AD B2C OpenID Connect metadata document
            token-uri: ${your-token-uri}
            # You can find your `jwkSetUri` from the result page of Azure AD B2C OpenID Connect metadata document
            jwk-set-uri: ${your-jwk-set-uri}
        registration:
          sign-up-or-sign-in:
            provider: sign-up-or-sign-in
            # Select your instance under `Applications` from portal, and then Fill in `${client-id}` from `Application ID`.
            # To make your accessToken can be validate form resource server, you should use the same application with resource server.
            client-id: ${client-id}
            # Fill in `${your-client-secret}` from one of `Keys`.
            client-secret: ${your-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            #Fill in `${client-id}` from `Application ID`
            scope: ${client-id}, openid, offline_access, profile

# this uri is used to clear your cache when you logout, please fill ${your-tenant-name} with your tenant name
# and fill ${policy-name} with your sign up or sign in user flow name.
logout-success-url: https://${your-tenant-name}.b2clogin.com/${your-tenant-name}.onmicrosoft.com/${policy-name}/oauth2/v2.0/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin