logging.level:
  org.springframework.security: TRACE

spring:
  docker:
    compose:
      file: classpath:docker/compose.yml
      readiness:
        wait: never
  security:
    saml2:
      relyingparty:
        registration:
          one:
            entity-id: "{baseUrl}/saml2/metadata"
            acs.location: "{baseUrl}/login/saml2/sso"
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            singlelogout:
              binding: REDIRECT
              url: "{baseUrl}/logout/saml2/slo"
            assertingparty.metadata-uri: http://idp-one.127-0-0-1.nip.io/simplesaml/saml2/idp/metadata.php
          two:
            entity-id: "{baseUrl}/saml2/metadata"
            acs.location: "{baseUrl}/login/saml2/sso"
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            singlelogout:
              binding: REDIRECT
              url: "{baseUrl}/logout/saml2/slo"
            assertingparty.metadata-uri: http://idp-two.127-0-0-1.nip.io/simplesaml/saml2/idp/metadata.php
