spring:
  application:
    name: magiclink
  mail:
    port: 1025
    host: localhost
  docker:
    compose:
      readiness:
        wait: never # for some reason it does not detect whether maildev is ready
      file: ./servlet/spring-boot/java/authentication/one-time-token/magic-link/compose.yml
