plugins {
	alias(libs.plugins.org.springframework.boot)
	alias(libs.plugins.io.spring.dependency.management)
	id 'java'
}

apply from: "$rootDir/gradle/integ-test.gradle"

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
	maven { url "https://repo.spring.io/snapshot" }
}


dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-test'
	implementation "org.testcontainers:testcontainers:1.20.3"
	implementation "org.testcontainers:junit-jupiter:1.20.3"
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
	
}
