= CAS Login & Logout Sample

This guide provides instructions on setting up an application that uses the CAS protocol for login.
It uses https://casserver.herokuapp.com/cas/login as the server supporting the CAS protocol.

The sample application uses Spring Boot and the `spring-security-cas`.

== Goals

=== CAS Login

`cas/login` provides a very simple implementation of a CAS Service (application) that use a public test CAS server for
 authentication.

The following features are implemented in the MVP:

1. Login
2. Logout

== Run the Sample

=== Start up the Sample Application in Tomcat with Gretty
[source,bash]
----
 ./gradlew :servlet:java-configuration:cas:login:appRun
----

=== Open a Browser

https://localhost:8443/

You will be redirect to a sample CAS server: https://casserver.herokuapp.com/cas

=== Type in the credentials

[source,bash]
----
User: casuser
Password: Mellon
----

=== Run a local CAS server
Run the following script to install and start a CAS server that responds at http://localhost:8090/cas/login

[source,bash]
----
servlet/java-configuration/cas/install-cas/install-cas.sh
----
or with Docker:
[source,bash]
----
servlet/java-configuration/cas/install-cas/run-cas-docker.sh
----

Adjust the `servlet/java-configuration/cas/login/src/main/resources/security.properties` file to point at local CAS server:

[source,bash]
----
cas.base.url=http://localhost:8090/cas
cas.login.url=http://localhost:8090/cas/login
----

Then run the CAS login app in gretty and browse to https://localhost:8443.

[source,bash]
----
 ./gradlew :servlet:java-configuration:cas:login:appRun
----
