name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # eventually add in matrix here
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Set up JDK
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@2fe291b7677a45ee1269ec56a42604c143505e7e # v1.3.0
      - name: Build with Gradle
        run: ./gradlew check --continue
